default_language_version:
  python: python3

exclude: |
  (?x)^(
    CODE_OF_CONDUCT.md
  )

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        exclude: |
          (?x)^(
            .*\.po$
          )
        additional_dependencies: [tomli]

  - repo: local
    hooks:
      - id: file-format
        name: file-format
        language: python
        entry: python .github/workflows/file_format.py
        types_or: [text]
